server:
  port: 8080
  servlet:
    context-path: '/medlinked-service/'

spring:
  application:
    name: medlinked-system
  datasource:
    url: jdbc:postgresql://localhost:5432/banco-med-linked
    username: postgres
    password: Key123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSqlDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  mail:
    host: smtp.gmail.com
    username: medlinked2023@gmail.com
    password: dbni wzpa auyt fyip
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
