server:
  port: 8080
  servlet:
    context-path: '/medlinked-service/'

spring:
  application:
    name: medlinked-system
  datasource:
    url: jdbc:postgresql://localhost:5432/banco-med-linked
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSqlDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true


