server:
  port: 8080
  servlet:
    context-path: '/medlinked-service/'

spring:
  application:
    name: medlinked-system
  datasource:
    url: "${env-spring-datasource-url}"
    username: "${env-spring-datasource-username}"
    password: "${env-spring-datasource-password}"
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSqlDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  mail:
    host: smtp.gmail.com
    username: "${env-spring-mail-username}"
    password: "${env-spring-mail-password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
